server {
    listen 80;
    listen [::]:80;
    server_name pool.shear.digital;
    root /var/www/pool.shear.digital;
    index index.html;
    location /api/ {
        proxy_pass http://127.0.0.1:8088;
    }
    location / { try_files $uri $uri/ @pool; }
    location @pool {
        proxy_pass http://127.0.0.1:8088;
    }
}
